#!/bin/bash

set -e
CURRENT_DIR=`pwd`
VERSION="1.0.1"
RELEASE_DATE="05-27-2016"

source config.sh
source setup_functions.sh
source depend_zlib.sh
source depend_openssl.sh
source depend_curl.sh

for i in "$@"
do
case $i in
	-v|--version)
		echo "acb-${VERSION}"
		exit 0
		shift # past argument=value
		;;
	-h|--help)
		show_help
		exit 0
		shift # past argument=value
		;;
	-ndk=*)
		NDK_DIR="${i#*=}"
		shift # past argument=value
		;;
	-android_platform=*)
		TOOLCHAIN_PLATFORM="${i#*=}"
		shift # past argument=value
		;;
	-toolchain=*)
		TOOLCHAIN_DIR="${i#*=}"
		shift # past argument=value
		;;
	-zlib_src=*)
		ZLIB_SOURCE_DIR="${i#*=}"
		shift # past argument=value
		;;
	-openssl_src=*)
		OPENSSL_SOURCE_DIR="${i#*=}"
		shift # past argument=value
		;;
	-curl_src=*)
		CURL_SOURCE_DIR="${i#*=}"
		shift # past argument=value
		;;
	-zlib_install=*)
		ZLIB_INSTALL_DIR="${i#*=}"
		shift # past argument=value
		;;
	-openssl_install=*)
		OPENSSL_INSTALL_DIR="${i#*=}"
		shift # past argument=value
		;;
	-curl_install=*)
		CURL_INSTALL_DIR="${i#*=}"
		shift # past argument=value
		;;
	-global_install=*)
		GLOBAL_INSTALL_DIR="${i#*=}"
		shift # past argument=value
		;;
	--disable-zlib-build)
		BUILD_ZLIB=0
		shift # past argument=value
		;;
	--disable-openssl-build)
		BUILD_OPENSSL=0
		shift # past argument=value
		;;
	*)
		# unknown option
		;;
esac
done

print_header
check_build_dependency
os_check
set_config
set_install_dir
setup_ndk
setup_toolchain
check_build_args
add_to_path

log_global_vars

if [ "$BUILD_INTERACTIVE" == 1 ]; then

	read -p "Do you want to build curl with these settings ? (y/n) " -n 1 -r
	echo
	if [[ ! $REPLY =~ ^[Yy]$ ]]
	then
		echo "> edit config.sh vars"
		exit 1
	fi
fi

if [ "$BUILD_ZLIB" == 1 ]; then
	depend_zlib
fi

if [ "$BUILD_OPENSSL" == 1 ]; then 
	depend_openssl
fi

depend_curl